/**
* JS Function Library
*/

class INFT_library {
    errors = {
        INFT_STATUS_MESSAGE : "INFT_STATUS_MESSAGE",
        INFT_ERROR_MESSAGE : "INFT_ERROR_MESSAGE",
        STATUS_USER_NOT_EXISTENT : "STATUS_USER_NOT_EXISTENT",
        STATUS_USER_ALREADY_REGISTERED : "STATUS_USER_ALREADY_REGISTERED",
        ERR_USER_ALREADY_REGISTERED : "ERR_USER_ALREADY_REGISTERED",
        ERR_USER_NOT_EXISTENT : "ERR_USER_NOT_EXISTENT",
    };
}

const INFT = new INFT_library();

module.exports = {
    INFT
}; 